import 'package:objectbox/objectbox.dart';
import 'package:syncara/data/models/media.dart';

import '../clients/yt_transcript_fetcher.dart';

@Entity()
class LyricMetadata {
  @Id()
  int objectId = 0;
  @Index()
  @Unique(onConflict: ConflictStrategy.replace)
  final String mediaID;
  final String lang, langCode;

  LyricMetadata(this.mediaID, this.lang, this.langCode);

  factory LyricMetadata.fromYTCaption(
    Media media,
    CaptionTrack cc,
  ) {
    return LyricMetadata(
      media.url,
      '${cc.languageCode} ${cc.isAutoGenerated ? '[Auto Generated]' : ''}',
      cc.languageCode,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricMetadata &&
          runtimeType == other.runtimeType &&
          mediaID == other.mediaID &&
          langCode == other.langCode &&
          lang == other.lang;

  @override
  int get hashCode => mediaID.hashCode ^ langCode.hashCode ^ lang.hashCode;
}

class LastPlayedMedia {
  final String playlistId;
  final String mediaId;

  LastPlayedMedia({
    required this.playlistId,
    required this.mediaId,
  });

  factory LastPlayedMedia.fromJson(Map<String, dynamic> json) =>
      LastPlayedMedia(
        playlistId: json["playlistId"] as String,
        mediaId: json["mediaId"] as String,
      );

  Map<String, dynamic> toJson() => {
    "playlistId": playlistId,
    "mediaId": mediaId,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LastPlayedMedia &&
          runtimeType == other.runtimeType &&
          playlistId == other.playlistId &&
          mediaId == other.mediaId;

  @override
  int get hashCode => playlistId.hashCode ^ mediaId.hashCode;
}

//ignore: constant_identifier_names
enum SortOption { Ascending, Descending, Reverse, Author, Reset }

//ignore: constant_identifier_names
enum NotificationCloseButton { Close, Shuffle, SeekForward, SeekBackward, None }

// ignore: constant_identifier_names
enum MiniPlayerExtraAction { Close, Shuffle, SeekForward, SeekBackward, None }
