// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../data/models/media.dart';
import '../data/models/playlist.dart';
import '../data/models/playlist_item.dart';
import '../model/common.dart';
import '../model/preferences.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7467807554909333142),
    name: 'Playlist',
    lastPropertyId: const obx_int.IdUid(16, 9039807171720259969),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2158148047630895875),
        name: 'objectId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 678632587378790868),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3982192456441633844),
        name: 'author',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6558476110564677998),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1741568516604972857),
        name: 'customTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1441901671507566634),
        name: 'url',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(12, 1356843290073877334),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5214987569187640464),
        name: 'itemCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8486132066345216977),
        name: 'thumbnail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 9039807171720259969),
        name: 'thumbnailHiRes',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4450489339876050059),
    name: 'LyricMetadata',
    lastPropertyId: const obx_int.IdUid(4, 3548921602646981933),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5980000064298778194),
        name: 'objectId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2617552261258508611),
        name: 'mediaID',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(9, 7353873539367616390),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2058926365234514082),
        name: 'lang',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3548921602646981933),
        name: 'langCode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 5309797750345703025),
    name: 'Preferences',
    lastPropertyId: const obx_int.IdUid(7, 2641593826290324090),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2678485310336356727),
        name: 'objectId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5407457566537552171),
        name: 'key',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(11, 279692091524021702),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3983703249591075078),
        name: 'stringValue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2467420716039857191),
        name: 'intValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4444840973718734749),
        name: 'doubleValue',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4779246458091017259),
        name: 'boolValue',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2641593826290324090),
        name: 'jsonValue',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 882847733899621766),
    name: 'PlaylistItem',
    lastPropertyId: const obx_int.IdUid(4, 7574123375628957182),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4406387199714115615),
        name: 'objectId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5950885231422011127),
        name: 'position',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6162112476034159306),
        name: 'playlistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(13, 3858651931344549030),
        relationTarget: 'Playlist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7574123375628957182),
        name: 'mediaId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 3541742103393101256),
        relationTarget: 'Media',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 71020629254117670),
    name: 'Media',
    lastPropertyId: const obx_int.IdUid(8, 8252122063568999386),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4831192096808569880),
        name: 'objectId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 766007872890872285),
        name: 'url',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(15, 6329407002244334835),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7765937904121424852),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5103752595000922783),
        name: 'author',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3134305048480575172),
        name: 'durationMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 829322747795626953),
        name: 'thumbnail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4844607176574051794),
        name: 'thumbnailHiRes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8252122063568999386),
        name: 'localPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 71020629254117670),
    lastIndexId: const obx_int.IdUid(15, 6329407002244334835),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      4737199419654631046,
      536188101098301761,
      6228540478334327525,
      8944036839846199287,
      7244206701017612236,
    ],
    retiredIndexUids: const [
      2015533167872099535,
      5028937706686708047,
      8199059820302370142,
      4887852901383162796,
    ],
    retiredPropertyUids: const [
      4068378090631746198,
      5531363271201020923,
      3963224645153264834,
      4950789527116186181,
      290261169854619342,
      4486176748003022356,
      1367197916984174054,
      6875212323207388660,
      1912405125313128972,
      7666746367792330762,
      4995326658066651107,
      2819376610628445258,
      6080131099321105811,
      7115588935925916806,
      3523529833173663526,
      7552649290287858908,
      8562407384505637413,
      2151538461643196514,
      7363821989914468133,
      8640752907744494080,
      7844790983954600126,
      1860228389517362730,
      7586969722204059133,
      6016108283348481869,
      7542159364117227975,
      4770024816285670442,
      6099949470292970003,
      6576783058116604137,
      3507134448911513332,
      2805903540978696307,
      3622381584134760667,
      5480825980133536831,
      9214425591051150229,
      5412057601330734262,
      5421354271517500275,
      8280104840695593580,
      6418265162038148102,
      3438048962647004832,
      5721380624281503879,
      1718917551870878083,
      1046998783511024043,
      7404903727434304676,
      6349290188780030319,
      7536243353200912842,
      8572832788458319135,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Playlist: obx_int.EntityDefinition<Playlist>(
      model: _entities[0],
      toOneRelations: (Playlist object) => [],
      toManyRelations: (Playlist object) => {},
      getId: (Playlist object) => object.objectId,
      setId: (Playlist object, int id) {
        object.objectId = id;
      },
      objectToFB: (Playlist object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final authorOffset = fbb.writeString(object.author);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final customTitleOffset = object.customTitle == null
            ? null
            : fbb.writeString(object.customTitle!);
        final urlOffset = fbb.writeString(object.url);
        final thumbnailOffset = fbb.writeString(object.thumbnail);
        final thumbnailHiResOffset = object.thumbnailHiRes == null
            ? null
            : fbb.writeString(object.thumbnailHiRes!);
        fbb.startTable(17);
        fbb.addInt64(0, object.objectId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, authorOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(10, customTitleOffset);
        fbb.addOffset(12, urlOffset);
        fbb.addInt64(13, object.itemCount);
        fbb.addOffset(14, thumbnailOffset);
        fbb.addOffset(15, thumbnailHiResOffset);
        fbb.finish(fbb.endTable());
        return object.objectId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final authorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final thumbnailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final thumbnailHiResParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final itemCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final customTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final object =
            Playlist(
                url: urlParam,
                title: titleParam,
                author: authorParam,
                thumbnail: thumbnailParam,
                thumbnailHiRes: thumbnailHiResParam,
                itemCount: itemCountParam,
                description: descriptionParam,
                customTitle: customTitleParam,
              )
              ..objectId = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                4,
                0,
              );

        return object;
      },
    ),
    LyricMetadata: obx_int.EntityDefinition<LyricMetadata>(
      model: _entities[1],
      toOneRelations: (LyricMetadata object) => [],
      toManyRelations: (LyricMetadata object) => {},
      getId: (LyricMetadata object) => object.objectId,
      setId: (LyricMetadata object, int id) {
        object.objectId = id;
      },
      objectToFB: (LyricMetadata object, fb.Builder fbb) {
        final mediaIDOffset = fbb.writeString(object.mediaID);
        final langOffset = fbb.writeString(object.lang);
        final langCodeOffset = fbb.writeString(object.langCode);
        fbb.startTable(5);
        fbb.addInt64(0, object.objectId);
        fbb.addOffset(1, mediaIDOffset);
        fbb.addOffset(2, langOffset);
        fbb.addOffset(3, langCodeOffset);
        fbb.finish(fbb.endTable());
        return object.objectId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final mediaIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final langParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final langCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = LyricMetadata(mediaIDParam, langParam, langCodeParam)
          ..objectId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            4,
            0,
          );

        return object;
      },
    ),
    Preferences: obx_int.EntityDefinition<Preferences>(
      model: _entities[2],
      toOneRelations: (Preferences object) => [],
      toManyRelations: (Preferences object) => {},
      getId: (Preferences object) => object.objectId,
      setId: (Preferences object, int id) {
        object.objectId = id;
      },
      objectToFB: (Preferences object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final stringValueOffset = object.stringValue == null
            ? null
            : fbb.writeString(object.stringValue!);
        final jsonValueOffset = object.jsonValue == null
            ? null
            : fbb.writeString(object.jsonValue!);
        fbb.startTable(8);
        fbb.addInt64(0, object.objectId);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, stringValueOffset);
        fbb.addInt64(3, object.intValue);
        fbb.addFloat64(4, object.doubleValue);
        fbb.addBool(5, object.boolValue);
        fbb.addOffset(6, jsonValueOffset);
        fbb.finish(fbb.endTable());
        return object.objectId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = Preferences(keyParam)
          ..objectId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            4,
            0,
          )
          ..stringValue = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..intValue = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            10,
          )
          ..doubleValue = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            12,
          )
          ..boolValue = const fb.BoolReader().vTableGetNullable(
            buffer,
            rootOffset,
            14,
          )
          ..jsonValue = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 16);

        return object;
      },
    ),
    PlaylistItem: obx_int.EntityDefinition<PlaylistItem>(
      model: _entities[3],
      toOneRelations: (PlaylistItem object) => [object.playlist, object.media],
      toManyRelations: (PlaylistItem object) => {},
      getId: (PlaylistItem object) => object.objectId,
      setId: (PlaylistItem object, int id) {
        object.objectId = id;
      },
      objectToFB: (PlaylistItem object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.objectId);
        fbb.addInt64(1, object.position);
        fbb.addInt64(2, object.playlist.targetId);
        fbb.addInt64(3, object.media.targetId);
        fbb.finish(fbb.endTable());
        return object.objectId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final positionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final object = PlaylistItem(position: positionParam)
          ..objectId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            4,
            0,
          );
        object.playlist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.playlist.attach(store);
        object.media.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.media.attach(store);
        return object;
      },
    ),
    Media: obx_int.EntityDefinition<Media>(
      model: _entities[4],
      toOneRelations: (Media object) => [],
      toManyRelations: (Media object) => {},
      getId: (Media object) => object.objectId,
      setId: (Media object, int id) {
        object.objectId = id;
      },
      objectToFB: (Media object, fb.Builder fbb) {
        final urlOffset = fbb.writeString(object.url);
        final titleOffset = fbb.writeString(object.title);
        final authorOffset = fbb.writeString(object.author);
        final thumbnailOffset = object.thumbnail == null
            ? null
            : fbb.writeString(object.thumbnail!);
        final thumbnailHiResOffset = object.thumbnailHiRes == null
            ? null
            : fbb.writeString(object.thumbnailHiRes!);
        final localPathOffset = object.localPath == null
            ? null
            : fbb.writeString(object.localPath!);
        fbb.startTable(9);
        fbb.addInt64(0, object.objectId);
        fbb.addOffset(1, urlOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, authorOffset);
        fbb.addInt64(4, object.durationMs);
        fbb.addOffset(5, thumbnailOffset);
        fbb.addOffset(6, thumbnailHiResOffset);
        fbb.addOffset(7, localPathOffset);
        fbb.finish(fbb.endTable());
        return object.objectId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final authorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final durationMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final thumbnailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final thumbnailHiResParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final localPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final object =
            Media(
                url: urlParam,
                title: titleParam,
                author: authorParam,
                durationMs: durationMsParam,
                thumbnail: thumbnailParam,
                thumbnailHiRes: thumbnailHiResParam,
                localPath: localPathParam,
              )
              ..objectId = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                4,
                0,
              );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Playlist] entity fields to define ObjectBox queries.
class Playlist_ {
  /// See [Playlist.objectId].
  static final objectId = obx.QueryIntegerProperty<Playlist>(
    _entities[0].properties[0],
  );

  /// See [Playlist.title].
  static final title = obx.QueryStringProperty<Playlist>(
    _entities[0].properties[1],
  );

  /// See [Playlist.author].
  static final author = obx.QueryStringProperty<Playlist>(
    _entities[0].properties[2],
  );

  /// See [Playlist.description].
  static final description = obx.QueryStringProperty<Playlist>(
    _entities[0].properties[3],
  );

  /// See [Playlist.customTitle].
  static final customTitle = obx.QueryStringProperty<Playlist>(
    _entities[0].properties[4],
  );

  /// See [Playlist.url].
  static final url = obx.QueryStringProperty<Playlist>(
    _entities[0].properties[5],
  );

  /// See [Playlist.itemCount].
  static final itemCount = obx.QueryIntegerProperty<Playlist>(
    _entities[0].properties[6],
  );

  /// See [Playlist.thumbnail].
  static final thumbnail = obx.QueryStringProperty<Playlist>(
    _entities[0].properties[7],
  );

  /// See [Playlist.thumbnailHiRes].
  static final thumbnailHiRes = obx.QueryStringProperty<Playlist>(
    _entities[0].properties[8],
  );
}

/// [LyricMetadata] entity fields to define ObjectBox queries.
class LyricMetadata_ {
  /// See [LyricMetadata.objectId].
  static final objectId = obx.QueryIntegerProperty<LyricMetadata>(
    _entities[1].properties[0],
  );

  /// See [LyricMetadata.mediaID].
  static final mediaID = obx.QueryStringProperty<LyricMetadata>(
    _entities[1].properties[1],
  );

  /// See [LyricMetadata.lang].
  static final lang = obx.QueryStringProperty<LyricMetadata>(
    _entities[1].properties[2],
  );

  /// See [LyricMetadata.langCode].
  static final langCode = obx.QueryStringProperty<LyricMetadata>(
    _entities[1].properties[3],
  );
}

/// [Preferences] entity fields to define ObjectBox queries.
class Preferences_ {
  /// See [Preferences.objectId].
  static final objectId = obx.QueryIntegerProperty<Preferences>(
    _entities[2].properties[0],
  );

  /// See [Preferences.key].
  static final key = obx.QueryStringProperty<Preferences>(
    _entities[2].properties[1],
  );

  /// See [Preferences.stringValue].
  static final stringValue = obx.QueryStringProperty<Preferences>(
    _entities[2].properties[2],
  );

  /// See [Preferences.intValue].
  static final intValue = obx.QueryIntegerProperty<Preferences>(
    _entities[2].properties[3],
  );

  /// See [Preferences.doubleValue].
  static final doubleValue = obx.QueryDoubleProperty<Preferences>(
    _entities[2].properties[4],
  );

  /// See [Preferences.boolValue].
  static final boolValue = obx.QueryBooleanProperty<Preferences>(
    _entities[2].properties[5],
  );

  /// See [Preferences.jsonValue].
  static final jsonValue = obx.QueryStringProperty<Preferences>(
    _entities[2].properties[6],
  );
}

/// [PlaylistItem] entity fields to define ObjectBox queries.
class PlaylistItem_ {
  /// See [PlaylistItem.objectId].
  static final objectId = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[3].properties[0],
  );

  /// See [PlaylistItem.position].
  static final position = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[3].properties[1],
  );

  /// See [PlaylistItem.playlist].
  static final playlist = obx.QueryRelationToOne<PlaylistItem, Playlist>(
    _entities[3].properties[2],
  );

  /// See [PlaylistItem.media].
  static final media = obx.QueryRelationToOne<PlaylistItem, Media>(
    _entities[3].properties[3],
  );
}

/// [Media] entity fields to define ObjectBox queries.
class Media_ {
  /// See [Media.objectId].
  static final objectId = obx.QueryIntegerProperty<Media>(
    _entities[4].properties[0],
  );

  /// See [Media.url].
  static final url = obx.QueryStringProperty<Media>(_entities[4].properties[1]);

  /// See [Media.title].
  static final title = obx.QueryStringProperty<Media>(
    _entities[4].properties[2],
  );

  /// See [Media.author].
  static final author = obx.QueryStringProperty<Media>(
    _entities[4].properties[3],
  );

  /// See [Media.durationMs].
  static final durationMs = obx.QueryIntegerProperty<Media>(
    _entities[4].properties[4],
  );

  /// See [Media.thumbnail].
  static final thumbnail = obx.QueryStringProperty<Media>(
    _entities[4].properties[5],
  );

  /// See [Media.thumbnailHiRes].
  static final thumbnailHiRes = obx.QueryStringProperty<Media>(
    _entities[4].properties[6],
  );

  /// See [Media.localPath].
  static final localPath = obx.QueryStringProperty<Media>(
    _entities[4].properties[7],
  );
}
